import { dir } from 'i18next';
import { Inter } from 'next/font/google';

import { languages } from '../../i18n/settings';

import type { Metadata } from 'next';
import type { ILayout } from './interfaces/IPage';

import './sass/globals.scss';

import Navigation from '@/app/[lng]/components/Navigation';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: {
    lng,
  },
}: ILayout) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <div className="w-full flex justify-center">
          <Navigation lang={lng} />
        </div>

        <div className="flex justify-center pt-10">
          {children}
        </div>
      </body>
    </html>
  );
}
